### ISSUE TITLE
Internal error

### ISSUE THREAD

**Issue by dmitrymaximov** [maxrossello/redmine_app_timesheets#50]
When I opening apps/timesheets page, I have got Internal error:
"Internal error

An error occurred on the page you were trying to access.
If you continue to experience problems please contact your Redmine administrator for assistance.

If you are the Redmine administrator, check your log files for details about the error."

Logs below:

Started GET "/apps/timelog" for 91.184.201.2 at Thu May 07 16:03:22 +0000 2015
Processing by TimelogController#index as HTML
  Current user: dmitry.maximov (id=73)
  Rendered queries/_filters.html.erb (236.0ms)
  Rendered queries/_columns.html.erb (2.8ms)
  Rendered timelog/_date_range.html.erb (242.0ms)
  Rendered timelog/_list.html.erb (1101.6ms)
  Rendered timelog/index.html.erb within layouts/base (1357.4ms)
Completed 200 OK in 1907.4ms (Views: 1609.9ms | ActiveRecord: 117.6ms)
Started GET "/settings/plugin/redmine_app__space" for 91.184.201.2 at Thu May 07 16:03:36 +0000 2015
Processing by SettingsController#plugin as HTML
  Parameters: {"id"=>"redmine_app__space"}
  Current user: dmitry.maximov (id=73)
  Rendered plugins/redmine_app__space/app/views/appspace/_application_settings.html.erb (42.2ms)
  Rendered settings/plugin.html.erb within layouts/admin (44.1ms)
  Rendered admin/_menu.html.erb (7.1ms)
  Rendered layouts/base.html.erb (285.5ms)
Completed 200 OK in 344.0ms (Views: 328.1ms | ActiveRecord: 12.2ms)
Started GET "/apps/timesheets" for 91.184.201.2 at Thu May 07 16:03:38 +0000 2015
Processing by TimesheetsController#index as HTML
  Current user: dmitry.maximov (id=73)
Completed 500 Internal Server Error in 43.5ms

NoMethodError (undefined method `keys' for []:Array):
  plugins/redmine_app_timesheets/app/controllers/timesheets_controller.rb:361:in `get_timelogs'
  activesupport (3.2.21) lib/active_support/callbacks.rb:528:in `_run__1008053545__process_action__317436796__callbacks'
  activesupport (3.2.21) lib/active_support/callbacks.rb:405:in `send'
  activesupport (3.2.21) lib/active_support/callbacks.rb:405:in `__run_callback'
  activesupport (3.2.21) lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
  activesupport (3.2.21) lib/active_support/callbacks.rb:81:in `send'
  activesupport (3.2.21) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (3.2.21) lib/abstract_controller/callbacks.rb:17:in `process_action'
  actionpack (3.2.21) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (3.2.21) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  activesupport (3.2.21) lib/active_support/notifications.rb:123:in `instrument'
  activesupport (3.2.21) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (3.2.21) lib/active_support/notifications.rb:123:in `instrument'
  actionpack (3.2.21) lib/action_controller/metal/instrumentation.rb:29:in `process_action'
  actionpack (3.2.21) lib/action_controller/metal/params_wrapper.rb:207:in `process_action'
  activerecord (3.2.21) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (3.2.21) lib/abstract_controller/base.rb:121:in `process'
  actionpack (3.2.21) lib/abstract_controller/rendering.rb:45:in `process'
  actionpack (3.2.21) lib/action_controller/metal.rb:203:in `dispatch'
  actionpack (3.2.21) lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
  actionpack (3.2.21) lib/action_controller/metal.rb:246:in `action'
  actionpack (3.2.21) lib/action_dispatch/routing/route_set.rb:73:in `call'
  actionpack (3.2.21) lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
  actionpack (3.2.21) lib/action_dispatch/routing/route_set.rb:36:in `call'
  journey (1.0.4) lib/journey/router.rb:68:in `call'
  journey (1.0.4) lib/journey/router.rb:56:in `each'
  journey (1.0.4) lib/journey/router.rb:56:in `call'
  actionpack (3.2.21) lib/action_dispatch/routing/route_set.rb:608:in `call'
  rack-openid (1.4.2) lib/rack/openid.rb:98:in `call'
  request_store (1.0.5) lib/request_store/middleware.rb:9:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
  rack (1.4.5) lib/rack/etag.rb:23:in `call'
  rack (1.4.5) lib/rack/conditionalget.rb:25:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/head.rb:14:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/params_parser.rb:21:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/flash.rb:242:in `call'
  rack (1.4.5) lib/rack/session/abstract/id.rb:210:in `context'
  rack (1.4.5) lib/rack/session/abstract/id.rb:205:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/cookies.rb:341:in `call'
  activerecord (3.2.21) lib/active_record/query_cache.rb:64:in `call'
  activerecord (3.2.21) lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/callbacks.rb:28:in `call'
  activesupport (3.2.21) lib/active_support/callbacks.rb:405:in `_run__1148042281__call__4__callbacks'
  activesupport (3.2.21) lib/active_support/callbacks.rb:405:in `send'
  activesupport (3.2.21) lib/active_support/callbacks.rb:405:in `__run_callback'
  activesupport (3.2.21) lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
  activesupport (3.2.21) lib/active_support/callbacks.rb:81:in `send'
  activesupport (3.2.21) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (3.2.21) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
  railties (3.2.21) lib/rails/rack/logger.rb:32:in `call_app'
  railties (3.2.21) lib/rails/rack/logger.rb:16:in `call'
  activesupport (3.2.21) lib/active_support/tagged_logging.rb:22:in `tagged'
  railties (3.2.21) lib/rails/rack/logger.rb:16:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/request_id.rb:22:in `call'
  rack (1.4.5) lib/rack/methodoverride.rb:21:in `call'
  rack (1.4.5) lib/rack/runtime.rb:17:in `call'
  activesupport (3.2.21) lib/active_support/cache/strategy/local_cache.rb:72:in `call'
  rack (1.4.5) lib/rack/lock.rb:15:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/static.rb:83:in `call'
  rack-cache (1.2) lib/rack/cache/context.rb:136:in `forward'
  rack-cache (1.2) lib/rack/cache/context.rb:245:in `fetch'
  rack-cache (1.2) lib/rack/cache/context.rb:185:in `lookup'
  rack-cache (1.2) lib/rack/cache/context.rb:66:in `call!'
  rack-cache (1.2) lib/rack/cache/context.rb:51:in `call'
  railties (3.2.21) lib/rails/engine.rb:484:in `call'
  railties (3.2.21) lib/rails/application.rb:231:in `call'
  railties (3.2.21) lib/rails/railtie/configurable.rb:30:in `send'
  railties (3.2.21) lib/rails/railtie/configurable.rb:30:in `method_missing'
  passenger (4.0.40) lib/phusion_passenger/rack/thread_handler_extension.rb:74:in `process_request'
  passenger (4.0.40) lib/phusion_passenger/request_handler/thread_handler.rb:141:in `accept_and_process_next_request'
  passenger (4.0.40) lib/phusion_passenger/request_handler/thread_handler.rb:109:in `main_loop'
  passenger (4.0.40) lib/phusion_passenger/request_handler.rb:448:in `start_threads'
  passenger (4.0.40) lib/phusion_passenger/request_handler.rb:442:in `initialize'
  passenger (4.0.40) lib/phusion_passenger/request_handler.rb:442:in `new'
  passenger (4.0.40) lib/phusion_passenger/request_handler.rb:442:in `start_threads'
  passenger (4.0.40) lib/phusion_passenger/request_handler.rb:441:in `times'
  passenger (4.0.40) lib/phusion_passenger/request_handler.rb:441:in `start_threads'
  passenger (4.0.40) lib/phusion_passenger/request_handler.rb:440:in `synchronize'
  passenger (4.0.40) lib/phusion_passenger/request_handler.rb:440:in `start_threads'
  passenger (4.0.40) lib/phusion_passenger/request_handler.rb:205:in `main_loop'
  passenger (4.0.40) helper-scripts/rack-preloader.rb:161

Started POST "/settings/plugin/redmine_app__space" for 91.184.201.2 at Thu May 07 16:04:08 +0000 2015
Processing by SettingsController#plugin as HTML
  Parameters: {"id"=>"redmine_app__space", "utf8"=>"✓", "commit"=>"Применить", "authenticity_token"=>"vW+t9Lu8qsznOpxYjD7luuX/VKH0I24bwuolABwl3fk=", "settings"=>{"auth_group"=>{"news"=>"192", "calendar"=>"192", "order_mgmt"=>"192", "timelog"=>"192", "timesheets"=>"192", "activity"=>"192", "issuesreportedbyme"=>"192", "issuesassignedtome"=>"192", "issueswatched"=>"192"}, "enabled"=>["order_mgmt", "timelog", "timesheets", "__dummy__"], "available"=>[{"partial"=>"my/blocks/issuesassignedtome", "name"=>"issuesassignedtome"}, {"name"=>"order_mgmt"}, {"partial"=>"my/blocks/issuesreportedbyme", "name"=>"issuesreportedbyme"}, {"name"=>"timelog"}, {"name"=>"timesheets"}, {"partial"=>"my/blocks/issueswatched", "name"=>"issueswatched"}, {"name"=>"activity"}, {"partial"=>"my/blocks/calendar", "name"=>"calendar"}, {"partial"=>"my/blocks/news", "name"=>"news"}]}}
  Current user: dmitry.maximov (id=73)
Redirected to https://***.com/settings/plugin/redmine_app__space
Completed 302 Found in 19.8ms (ActiveRecord: 7.1ms)
Started GET "/settings/plugin/redmine_app__space" for 91.184.201.2 at Thu May 07 16:04:08 +0000 2015
Processing by SettingsController#plugin as HTML
  Parameters: {"id"=>"redmine_app__space"}
Settings cache cleared.
  Current user: dmitry.maximov (id=73)
  Rendered plugins/redmine_app__space/app/views/appspace/_application_settings.html.erb (254.8ms)
  Rendered settings/plugin.html.erb within layouts/admin (257.2ms)
  Rendered admin/_menu.html.erb (7.0ms)
  Rendered layouts/base.html.erb (90.5ms)
Completed 200 OK in 366.3ms (Views: 344.9ms | ActiveRecord: 15.1ms)
Started GET "/apps/timesheets" for 91.184.201.2 at Thu May 07 16:04:09 +0000 2015
Processing by TimesheetsController#index as HTML
  Current user: dmitry.maximov (id=73)
Completed 500 Internal Server Error in 255.5ms

NoMethodError (undefined method `keys' for []:Array):
  plugins/redmine_app_timesheets/app/controllers/timesheets_controller.rb:361:in `get_timelogs'
  activesupport (3.2.21) lib/active_support/callbacks.rb:528:in `_run__1008053545__process_action__317436796__callbacks'
  activesupport (3.2.21) lib/active_support/callbacks.rb:405:in `send'
  activesupport (3.2.21) lib/active_support/callbacks.rb:405:in `__run_callback'
  activesupport (3.2.21) lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
  activesupport (3.2.21) lib/active_support/callbacks.rb:81:in `send'
  activesupport (3.2.21) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (3.2.21) lib/abstract_controller/callbacks.rb:17:in `process_action'
  actionpack (3.2.21) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (3.2.21) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  activesupport (3.2.21) lib/active_support/notifications.rb:123:in `instrument'
  activesupport (3.2.21) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (3.2.21) lib/active_support/notifications.rb:123:in `instrument'
  actionpack (3.2.21) lib/action_controller/metal/instrumentation.rb:29:in `process_action'
  actionpack (3.2.21) lib/action_controller/metal/params_wrapper.rb:207:in `process_action'
  activerecord (3.2.21) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (3.2.21) lib/abstract_controller/base.rb:121:in `process'
  actionpack (3.2.21) lib/abstract_controller/rendering.rb:45:in `process'
  actionpack (3.2.21) lib/action_controller/metal.rb:203:in `dispatch'
  actionpack (3.2.21) lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
  actionpack (3.2.21) lib/action_controller/metal.rb:246:in `action'
  actionpack (3.2.21) lib/action_dispatch/routing/route_set.rb:73:in `call'
  actionpack (3.2.21) lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
  actionpack (3.2.21) lib/action_dispatch/routing/route_set.rb:36:in `call'
  journey (1.0.4) lib/journey/router.rb:68:in `call'
  journey (1.0.4) lib/journey/router.rb:56:in `each'
  journey (1.0.4) lib/journey/router.rb:56:in `call'
  actionpack (3.2.21) lib/action_dispatch/routing/route_set.rb:608:in `call'
  rack-openid (1.4.2) lib/rack/openid.rb:98:in `call'
  request_store (1.0.5) lib/request_store/middleware.rb:9:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
  rack (1.4.5) lib/rack/etag.rb:23:in `call'
  rack (1.4.5) lib/rack/conditionalget.rb:25:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/head.rb:14:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/params_parser.rb:21:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/flash.rb:242:in `call'
  rack (1.4.5) lib/rack/session/abstract/id.rb:210:in `context'
  rack (1.4.5) lib/rack/session/abstract/id.rb:205:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/cookies.rb:341:in `call'
  activerecord (3.2.21) lib/active_record/query_cache.rb:64:in `call'
  activerecord (3.2.21) lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/callbacks.rb:28:in `call'
  activesupport (3.2.21) lib/active_support/callbacks.rb:405:in `_run__1148042281__call__4__callbacks'
  activesupport (3.2.21) lib/active_support/callbacks.rb:405:in `send'
  activesupport (3.2.21) lib/active_support/callbacks.rb:405:in `__run_callback'
  activesupport (3.2.21) lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
  activesupport (3.2.21) lib/active_support/callbacks.rb:81:in `send'
  activesupport (3.2.21) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (3.2.21) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
  railties (3.2.21) lib/rails/rack/logger.rb:32:in `call_app'
  railties (3.2.21) lib/rails/rack/logger.rb:16:in `call'
  activesupport (3.2.21) lib/active_support/tagged_logging.rb:22:in `tagged'
  railties (3.2.21) lib/rails/rack/logger.rb:16:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/request_id.rb:22:in `call'
  rack (1.4.5) lib/rack/methodoverride.rb:21:in `call'
  rack (1.4.5) lib/rack/runtime.rb:17:in `call'
  activesupport (3.2.21) lib/active_support/cache/strategy/local_cache.rb:72:in `call'
  rack (1.4.5) lib/rack/lock.rb:15:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/static.rb:83:in `call'
  rack-cache (1.2) lib/rack/cache/context.rb:136:in `forward'
  rack-cache (1.2) lib/rack/cache/context.rb:245:in `fetch'
  rack-cache (1.2) lib/rack/cache/context.rb:185:in `lookup'
  rack-cache (1.2) lib/rack/cache/context.rb:66:in `call!'
  rack-cache (1.2) lib/rack/cache/context.rb:51:in `call'
  railties (3.2.21) lib/rails/engine.rb:484:in `call'
  railties (3.2.21) lib/rails/application.rb:231:in `call'
  railties (3.2.21) lib/rails/railtie/configurable.rb:30:in `send'
  railties (3.2.21) lib/rails/railtie/configurable.rb:30:in `method_missing'
  passenger (4.0.40) lib/phusion_passenger/rack/thread_handler_extension.rb:74:in `process_request'
  passenger (4.0.40) lib/phusion_passenger/request_handler/thread_handler.rb:141:in `accept_and_process_next_request'
  passenger (4.0.40) lib/phusion_passenger/request_handler/thread_handler.rb:109:in `main_loop'
  passenger (4.0.40) lib/phusion_passenger/request_handler.rb:448:in `start_threads'
  passenger (4.0.40) lib/phusion_passenger/request_handler.rb:442:in `initialize'
  passenger (4.0.40) lib/phusion_passenger/request_handler.rb:442:in `new'
  passenger (4.0.40) lib/phusion_passenger/request_handler.rb:442:in `start_threads'
  passenger (4.0.40) lib/phusion_passenger/request_handler.rb:441:in `times'
  passenger (4.0.40) lib/phusion_passenger/request_handler.rb:441:in `start_threads'
  passenger (4.0.40) lib/phusion_passenger/request_handler.rb:440:in `synchronize'
  passenger (4.0.40) lib/phusion_passenger/request_handler.rb:440:in `start_threads'
  passenger (4.0.40) lib/phusion_passenger/request_handler.rb:205:in `main_loop'
  passenger (4.0.40) helper-scripts/rack-preloader.rb:161

Started GET "/apps/timelog" for 91.184.201.2 at Thu May 07 16:04:15 +0000 2015
Processing by TimelogController#index as HTML
  Current user: dmitry.maximov (id=73)
  Rendered queries/_filters.html.erb (39.5ms)
  Rendered queries/_columns.html.erb (202.4ms)
  Rendered timelog/_date_range.html.erb (244.3ms)
  Rendered timelog/_list.html.erb (1111.8ms)
  Rendered timelog/index.html.erb within layouts/base (1371.9ms)
Completed 200 OK in 1947.5ms (Views: 1634.5ms | ActiveRecord: 120.1ms)
Started GET "/settings/plugin/redmine_app__space" for 91.184.201.2 at Thu May 07 16:05:02 +0000 2015
Processing by SettingsController#plugin as HTML
  Parameters: {"id"=>"redmine_app__space"}
  Current user: dmitry.maximov (id=73)
  Rendered plugins/redmine_app__space/app/views/appspace/_application_settings.html.erb (43.6ms)
  Rendered settings/plugin.html.erb within layouts/admin (45.5ms)
  Rendered admin/_menu.html.erb (6.7ms)
  Rendered layouts/base.html.erb (290.6ms)
Completed 200 OK in 350.0ms (Views: 333.5ms | ActiveRecord: 12.8ms)

**Comment by dmitrymaximov** [comment]
Redmine verstion is 2.6.4.stable

**Comment by maxrossello** [comment]
What version of ruby are you using?

**Comment by dmitrymaximov** [comment]
Environment:
Redmine version - 2.6.4.stable
Ruby version - 1.8.7-p374 (2013-06-27) [x86_64-linux]
Rails version - 3.2.21

**Comment by maxrossello** [comment]
Ok, that's probably why your empty orders permissions result in an array [] rather than an hash {}

is it a problem for you trying to upgrade to at least ruby-1.9.3-p392?

**Comment by maxrossello** [comment]
Did this work for you?

**Comment by dmitrymaximov** [comment]
It is the same issue with this config:
Environment:
  Redmine version                3.0.2.stable
  Ruby version                   2.2.1-p85 (2015-02-26) [x86_64-linux]
  Rails version                  4.2.1
  Environment                    production
  Database adapter               PostgreSQL

**Comment by maxrossello** [comment]
Ok, I think you can go on if you add some order. In the meanwhile, I will make some test with an empty orders set.

**Comment by maxrossello** [comment]
Edited the title since I verified that the problem does not happen with a MySQL database.
