### ISSUE TITLE
Uninstall aborted

### ISSUE THREAD

**Issue by tmc9031** [maxrossello/redmine_app_timesheets#76]
test in redmine 3.0.7 and 3.1.5

```
$ bundle exec rake redmine:plugins:migrate NAME=redmine_app_timesheets VERSION=0 RAILS_ENV=production
Migrating redmine_app_timesheets (Redmine Timesheets Application)...
== 12 VersionIsOrder: reverting ===============================================
-- remove_column(:versions, :is_order)
   -> 0.0598s
== 12 VersionIsOrder: reverted (0.1045s) ======================================

== 11 TsRemoveIssues: reverting ===============================================
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

ActiveRecord::IrreversibleMigration
/home/ubuntu/app/redmine-2.6.10/plugins/redmine_app_timesheets/db/migrate/011_ts_remove_issues.rb:11:in `down'
/home/ubuntu/app/redmine-2.6.10/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.3/lib/active_record/migration.rb:608:in `exec_migration'
/home/ubuntu/app/redmine-2.6.10/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.3/lib/active_record/migration.rb:589:in `block (2 levels) in migrate'
/home/ubuntu/app/redmine-2.6.10/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.3/lib/active_record/migration.rb:588:in `block in migrate'
/home/ubuntu/app/redmine-2.6.10/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/home/ubuntu/app/redmine-2.6.10/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.3/lib/active_record/migration.rb:587:in `migrate'
/home/ubuntu/app/redmine-2.6.10/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.3/lib/active_record/migration.rb:764:in `migrate'
/home/ubuntu/app/redmine-2.6.10/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.3/lib/active_record/migration.rb:994:in `block in execute_migration_in_transaction'
/home/ubuntu/app/redmine-2.6.10/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.3/lib/active_record/migration.rb:1042:in `ddl_transaction'
/home/ubuntu/app/redmine-2.6.10/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.3/lib/active_record/migration.rb:993:in `execute_migration_in_transaction'
/home/ubuntu/app/redmine-2.6.10/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.3/lib/active_record/migration.rb:955:in `block in migrate'
/home/ubuntu/app/redmine-2.6.10/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.3/lib/active_record/migration.rb:951:in `each'
/home/ubuntu/app/redmine-2.6.10/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.3/lib/active_record/migration.rb:951:in `migrate'
/home/ubuntu/app/redmine-2.6.10/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.3/lib/active_record/migration.rb:826:in `down'
/home/ubuntu/app/redmine-2.6.10/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.3/lib/active_record/migration.rb:801:in `migrate'
/home/ubuntu/app/redmine-2.6.10/lib/redmine/plugin.rb:474:in `migrate_plugin'
/home/ubuntu/app/redmine-2.6.10/lib/redmine/plugin.rb:446:in `migrate'
/home/ubuntu/app/redmine-2.6.10/lib/redmine/plugin.rb:457:in `migrate'
/home/ubuntu/app/redmine-2.6.10/lib/tasks/redmine.rake:127:in `block (3 levels) in <top (required)>'
/home/ubuntu/opt/ruby/bin/bundle:23:in `load'
/home/ubuntu/opt/ruby/bin/bundle:23:in `<main>'
ActiveRecord::IrreversibleMigration: ActiveRecord::IrreversibleMigration
/home/ubuntu/app/redmine-2.6.10/plugins/redmine_app_timesheets/db/migrate/011_ts_remove_issues.rb:11:in `down'
/home/ubuntu/app/redmine-2.6.10/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.3/lib/active_record/migration.rb:608:in `exec_migration'
/home/ubuntu/app/redmine-2.6.10/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.3/lib/active_record/migration.rb:589:in `block (2 levels) in migrate'
/home/ubuntu/app/redmine-2.6.10/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.3/lib/active_record/migration.rb:588:in `block in migrate'
/home/ubuntu/app/redmine-2.6.10/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/home/ubuntu/app/redmine-2.6.10/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.3/lib/active_record/migration.rb:587:in `migrate'
/home/ubuntu/app/redmine-2.6.10/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.3/lib/active_record/migration.rb:764:in `migrate'
/home/ubuntu/app/redmine-2.6.10/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.3/lib/active_record/migration.rb:994:in `block in execute_migration_in_transaction'
/home/ubuntu/app/redmine-2.6.10/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.3/lib/active_record/migration.rb:1042:in `ddl_transaction'
/home/ubuntu/app/redmine-2.6.10/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.3/lib/active_record/migration.rb:993:in `execute_migration_in_transaction'
/home/ubuntu/app/redmine-2.6.10/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.3/lib/active_record/migration.rb:955:in `block in migrate'
/home/ubuntu/app/redmine-2.6.10/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.3/lib/active_record/migration.rb:951:in `each'
/home/ubuntu/app/redmine-2.6.10/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.3/lib/active_record/migration.rb:951:in `migrate'
/home/ubuntu/app/redmine-2.6.10/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.3/lib/active_record/migration.rb:826:in `down'
/home/ubuntu/app/redmine-2.6.10/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.3/lib/active_record/migration.rb:801:in `migrate'
/home/ubuntu/app/redmine-2.6.10/lib/redmine/plugin.rb:474:in `migrate_plugin'
/home/ubuntu/app/redmine-2.6.10/lib/redmine/plugin.rb:446:in `migrate'
/home/ubuntu/app/redmine-2.6.10/lib/redmine/plugin.rb:457:in `migrate'
/home/ubuntu/app/redmine-2.6.10/lib/tasks/redmine.rake:127:in `block (3 levels) in <top (required)>'
/home/ubuntu/opt/ruby/bin/bundle:23:in `load'
/home/ubuntu/opt/ruby/bin/bundle:23:in `<main>'
Tasks: TOP => redmine:plugins:migrate
(See full trace by running task with --trace)
```

**Comment by tmc9031** [comment]
add --trace log

```
$ RAILS_ENV=production bundle exec rake redmine:plugins:migrate NAME=redmine_app_timesheets VERSION=0 --trace
** Invoke redmine:plugins:migrate (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute redmine:plugins:migrate
Migrating redmine_app_timesheets (Redmine Timesheets Application)...
== 11 TsRemoveIssues: reverting ===============================================
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

ActiveRecord::IrreversibleMigration
/home/ubuntu/git/redmine/plugins/redmine_app_timesheets/db/migrate/011_ts_remove_issues.rb:11:in `down'
/home/ubuntu/git/redmine/vendor/bundle/ruby/2.0.0/gems/activerecord-4.2.3/lib/active_record/migration.rb:608:in `exec_migration'
/home/ubuntu/git/redmine/vendor/bundle/ruby/2.0.0/gems/activerecord-4.2.3/lib/active_record/migration.rb:589:in `block (2 levels) in migrate'
/home/ubuntu/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/2.0.0/benchmark.rb:281:in `measure'
/home/ubuntu/git/redmine/vendor/bundle/ruby/2.0.0/gems/activerecord-4.2.3/lib/active_record/migration.rb:588:in `block in migrate'
/home/ubuntu/git/redmine/vendor/bundle/ruby/2.0.0/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/home/ubuntu/git/redmine/vendor/bundle/ruby/2.0.0/gems/activerecord-4.2.3/lib/active_record/migration.rb:587:in `migrate'
/home/ubuntu/git/redmine/vendor/bundle/ruby/2.0.0/gems/activerecord-4.2.3/lib/active_record/migration.rb:764:in `migrate'
/home/ubuntu/git/redmine/vendor/bundle/ruby/2.0.0/gems/activerecord-4.2.3/lib/active_record/migration.rb:994:in `block in execute_migration_in_transaction'
/home/ubuntu/git/redmine/vendor/bundle/ruby/2.0.0/gems/activerecord-4.2.3/lib/active_record/migration.rb:1042:in `ddl_transaction'
/home/ubuntu/git/redmine/vendor/bundle/ruby/2.0.0/gems/activerecord-4.2.3/lib/active_record/migration.rb:993:in `execute_migration_in_transaction'
/home/ubuntu/git/redmine/vendor/bundle/ruby/2.0.0/gems/activerecord-4.2.3/lib/active_record/migration.rb:955:in `block in migrate'
/home/ubuntu/git/redmine/vendor/bundle/ruby/2.0.0/gems/activerecord-4.2.3/lib/active_record/migration.rb:951:in `each'
/home/ubuntu/git/redmine/vendor/bundle/ruby/2.0.0/gems/activerecord-4.2.3/lib/active_record/migration.rb:951:in `migrate'
/home/ubuntu/git/redmine/vendor/bundle/ruby/2.0.0/gems/activerecord-4.2.3/lib/active_record/migration.rb:826:in `down'
/home/ubuntu/git/redmine/vendor/bundle/ruby/2.0.0/gems/activerecord-4.2.3/lib/active_record/migration.rb:801:in `migrate'
/home/ubuntu/git/redmine/lib/redmine/plugin.rb:474:in `migrate_plugin'
/home/ubuntu/git/redmine/lib/redmine/plugin.rb:446:in `migrate'
/home/ubuntu/git/redmine/lib/redmine/plugin.rb:457:in `migrate'
/home/ubuntu/git/redmine/lib/tasks/redmine.rake:127:in `block (3 levels) in <top (required)>'
/home/ubuntu/git/redmine/vendor/bundle/ruby/2.0.0/gems/rake-11.1.2/lib/rake/task.rb:248:in `call'
/home/ubuntu/git/redmine/vendor/bundle/ruby/2.0.0/gems/rake-11.1.2/lib/rake/task.rb:248:in `block in execute'
/home/ubuntu/git/redmine/vendor/bundle/ruby/2.0.0/gems/rake-11.1.2/lib/rake/task.rb:243:in `each'
/home/ubuntu/git/redmine/vendor/bundle/ruby/2.0.0/gems/rake-11.1.2/lib/rake/task.rb:243:in `execute'
/home/ubuntu/git/redmine/vendor/bundle/ruby/2.0.0/gems/rake-11.1.2/lib/rake/task.rb:187:in `block in invoke_with_call_chain'
/home/ubuntu/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/2.0.0/monitor.rb:211:in `mon_synchronize'
/home/ubuntu/git/redmine/vendor/bundle/ruby/2.0.0/gems/rake-11.1.2/lib/rake/task.rb:180:in `invoke_with_call_chain'
/home/ubuntu/git/redmine/vendor/bundle/ruby/2.0.0/gems/rake-11.1.2/lib/rake/task.rb:173:in `invoke'
/home/ubuntu/git/redmine/vendor/bundle/ruby/2.0.0/gems/rake-11.1.2/lib/rake/application.rb:150:in `invoke_task'
/home/ubuntu/git/redmine/vendor/bundle/ruby/2.0.0/gems/rake-11.1.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/home/ubuntu/git/redmine/vendor/bundle/ruby/2.0.0/gems/rake-11.1.2/lib/rake/application.rb:106:in `each'
/home/ubuntu/git/redmine/vendor/bundle/ruby/2.0.0/gems/rake-11.1.2/lib/rake/application.rb:106:in `block in top_level'
/home/ubuntu/git/redmine/vendor/bundle/ruby/2.0.0/gems/rake-11.1.2/lib/rake/application.rb:115:in `run_with_threads'
/home/ubuntu/git/redmine/vendor/bundle/ruby/2.0.0/gems/rake-11.1.2/lib/rake/application.rb:100:in `top_level'
/home/ubuntu/git/redmine/vendor/bundle/ruby/2.0.0/gems/rake-11.1.2/lib/rake/application.rb:78:in `block in run'
/home/ubuntu/git/redmine/vendor/bundle/ruby/2.0.0/gems/rake-11.1.2/lib/rake/application.rb:176:in `standard_exception_handling'
/home/ubuntu/git/redmine/vendor/bundle/ruby/2.0.0/gems/rake-11.1.2/lib/rake/application.rb:75:in `run'
/home/ubuntu/git/redmine/vendor/bundle/ruby/2.0.0/gems/rake-11.1.2/bin/rake:33:in `<top (required)>'
/home/ubuntu/git/redmine/vendor/bundle/ruby/2.0.0/bin/rake:23:in `load'
/home/ubuntu/git/redmine/vendor/bundle/ruby/2.0.0/bin/rake:23:in `<top (required)>'
/home/ubuntu/.rvm/gems/ruby-2.0.0-p648/gems/bundler-1.12.3/lib/bundler/cli/exec.rb:63:in `load'
/home/ubuntu/.rvm/gems/ruby-2.0.0-p648/gems/bundler-1.12.3/lib/bundler/cli/exec.rb:63:in `kernel_load'
/home/ubuntu/.rvm/gems/ruby-2.0.0-p648/gems/bundler-1.12.3/lib/bundler/cli/exec.rb:24:in `run'
/home/ubuntu/.rvm/gems/ruby-2.0.0-p648/gems/bundler-1.12.3/lib/bundler/cli.rb:304:in `exec'
/home/ubuntu/.rvm/gems/ruby-2.0.0-p648/gems/bundler-1.12.3/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/home/ubuntu/.rvm/gems/ruby-2.0.0-p648/gems/bundler-1.12.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/home/ubuntu/.rvm/gems/ruby-2.0.0-p648/gems/bundler-1.12.3/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/home/ubuntu/.rvm/gems/ruby-2.0.0-p648/gems/bundler-1.12.3/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/home/ubuntu/.rvm/gems/ruby-2.0.0-p648/gems/bundler-1.12.3/lib/bundler/cli.rb:11:in `start'
/home/ubuntu/.rvm/gems/ruby-2.0.0-p648/gems/bundler-1.12.3/exe/bundle:27:in `block in <top (required)>'
/home/ubuntu/.rvm/gems/ruby-2.0.0-p648/gems/bundler-1.12.3/lib/bundler/friendly_errors.rb:98:in `with_friendly_errors'
/home/ubuntu/.rvm/gems/ruby-2.0.0-p648/gems/bundler-1.12.3/exe/bundle:19:in `<top (required)>'
/home/ubuntu/.rvm/gems/ruby-2.0.0-p648/bin/bundle:23:in `load'
/home/ubuntu/.rvm/gems/ruby-2.0.0-p648/bin/bundle:23:in `<main>'
/home/ubuntu/.rvm/gems/ruby-2.0.0-p648/bin/ruby_executable_hooks:15:in `eval'
/home/ubuntu/.rvm/gems/ruby-2.0.0-p648/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => redmine:plugins:migrate
```

**Comment by tmc9031** [comment]
use version
* 1.4_stable                d8828d1 [origin/1.4_stable] Modified README for 1.4_stable branch

**Comment by maxrossello** [comment]
Yes, the irreversible migration was added because it would have caused loss of information in case of revert to an older version. But, it also prevents to completely uninstall the plugin.

I'll fix this when I will have time to, but for the moment you can safely uninstall by commenting the IrreversibleMigration exception in the down action into db/migrate/011_ts_remove_issues.rb

regards
